apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: $DB_HOST
    user: $DB_USER
    secureJsonData:
      password: $DB_PASSWORD
    jsonData:
      database: $DB_NAME
      sslmode: "require" # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 16
      timescaledb: false
